server:
    port: 8080

spring:
  application:
        name: gateway
#    profiles:
#        include: commons
#        active: eureka-peer,feign
  main:
      web-application-type: reactive # 项目里依赖的web需要设置次属性
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
#        locator:
#          enabled: true
#          filters:
#            - args[name]: serviceId
#              name: CircuitBreaker
#            - args[regexp]: '"''/'' + serviceId + ''/?(?<remaining>.*)''"'
#              args[replacement]: '"''/${remaining}''"'
#              name: RewritePath
#          predicates:
#            - args[pattern]: '"''/''+serviceId+''/**''"'
#              name: Path
#            - args[pattern]: '"''**.foo.com''"'
#              name: Host
      routes: # 路由
        - id: hello
          uri: lb://hello
          predicates:
            - Path=/hello/**, /api/hello/**
#          filters:
#            - RewritePath=/hello/v3/?(?<segment>.*), /v3/$\{segment}
        - id: world
          uri: lb://world
          predicates:
            - Path=/hello/**, /api/world/**
          filters:
            - name: RequestRateLimiter
              args:
                deny-empty-key: false
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
      enabled: true
      default-filters:
        - name: RequestRateLimiter
          args:
            deny-empty-key: false
            key-resolver: "#{@userKeyResolver}"
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1
            redis-rate-limiter.requestedTokens: 1
  redis:
    host: 127.0.0.1
    port: 6379
