server:
    port: 8082

spring:
    application:
        name: world
    cloud:
        nacos:
            config:
                server-addr: 127.0.0.1:8848
                import-check:
                    enabled: false
            discovery:
                server-addr: 127.0.0.1:8848
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
springfox:
    documentation:
        open-api:
            v3:
                path: /api/${spring.application.name}/v3/api-docs