server:
    port: 8084

spring:
    application:
        name: hello

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS